runtime: nodejs20 # Adjust according to the Node.js version you're using

# Optional: specify the entry point file if it's different from server.js
entrypoint: node app.js

# Environment variables
env_variables:
  NODE_ENV: 'production'

# Optional: configure automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Optional: enable Google App Engine managed VPC access for database
# vpc_access_connector:
#   name: "projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME"

# Ensure only HTTPS connections are allowed
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
