export const FETCH_AUTOCOMPLETE_DATA = "FETCH_AUTOCOMPLETE_DATA";
export const FETCH_AUTOCOMPLETE_DATA_SUCCESS = "FETCH_AUTOCOMPLETE_DATA_SUCCESS";
export const FETCH_AUTOCOMPLETE_DATA_FAILURE = "FETCH_AUTOCOMPLETE_DATA_FAILURE";

export const TOGGLE_DETAILS_RESULTS_TAB = "TOGGLE_DETAILS_RESULTS_TAB";
export const RETURN_RESULTS_TAB = "RETURN_RESULTS_TAB";
export const TOGGLE_RESULTS_FAV_TAB = "TOGGLE_RESULTS_FAV_TAB";

export const FETCH_GEOCODE_DATA = "FETCH_GEOCODE_DATA";
export const FETCH_GEOCODE_DATA_SUCCESS = "FETCH_GEOCODE_DATA_SUCCESS";
export const FETCH_GEOCODE_DATA_FAILURE = "FETCH_GEOCODE_DATA_FAILURE";

export const FETCH_IPINFO_DATA = "FETCH_IPINFO_DATA";
export const FETCH_IPINFO_DATA_SUCCESS = "FETCH_IPINFO_DATA_SUCCESS";
export const FETCH_IPINFO_LATLNG_SUCCESS = "FETCH_IPINFO_LATLNG_SUCCESS";
export const FETCH_IPINFO_DATA_FAILURE = "FETCH_IPINFO_DATA_FAILURE";

export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_FAILURE = "FETCH_WEATHER_DATA_FAILURE";

export const FETCH_FAVORITES_DATA = "FETCH_FAVORITES_DATA";
export const FETCH_FAVORITES_DATA_SUCCESS = "FETCH_FAVORITES_DATA_SUCCESS";
export const FETCH_FAVORITES_DATA_FAILURE = "FETCH_FAVORITES_DATA_FAILURE";

export const ADD_FAVORITES_DATA = "ADD_FAVORITES_DATA";
export const ADD_FAVORITES_DATA_SUCCESS = "ADD_FAVORITES_DATA_SUCCESS";
export const ADD_FAVORITES_DATA_FAILURE = "ADD_FAVORITES_DATA_FAILURE";

export const DELETE_FAVORITES_DATA = "DELETE_FAVORITES_DATA";
export const DELETE_FAVORITES_DATA_SUCCESS = "DELETE_FAVORITES_DATA_SUCCESS";
export const DELETE_FAVORITES_DATA_FAILURE = "DELETE_FAVORITES_DATA_FAILURE";

export const NO_RECORDS_FOUND = "NO_RECORDS_FOUND";
export const RECORDS_FOUND = "RECORDS_FOUND";

export const PROGRESS_UPDATE = "PROGRESS_UPDATE";
export const PROGRESS = "PROGRESS";
